name: personal_website
description: Playgroud
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Theme
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1

  # State
  flutter_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4

  # Routing
  go_router: ^12.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Network
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/wordle-5-letter-list.json
    - lib/
    - lib/base/app_bar/
    - lib/pages/home/components/