// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKp4GHmmq09z7-Jt44UX9NBYIrSKs5KKI',
    appId: '1:265396258247:web:99c5ae750426824bdd45e2',
    messagingSenderId: '265396258247',
    projectId: 'personal-tommaso2212',
    authDomain: 'personal-tommaso2212.firebaseapp.com',
    storageBucket: 'personal-tommaso2212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hauhmpL7ikwBtG4Akvgrx5c_-mZ83O4',
    appId: '1:265396258247:android:1ecc179b8e723e97dd45e2',
    messagingSenderId: '265396258247',
    projectId: 'personal-tommaso2212',
    storageBucket: 'personal-tommaso2212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Tm1p9dIoRC0I-qh-oizI-lkW_PDTpEQ',
    appId: '1:265396258247:ios:b2d948feaa92ea30dd45e2',
    messagingSenderId: '265396258247',
    projectId: 'personal-tommaso2212',
    storageBucket: 'personal-tommaso2212.appspot.com',
    iosClientId: '265396258247-bi6k0eqornnl87dl1113mqo993ngoeio.apps.googleusercontent.com',
    iosBundleId: 'com.example.personal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Tm1p9dIoRC0I-qh-oizI-lkW_PDTpEQ',
    appId: '1:265396258247:ios:b2d948feaa92ea30dd45e2',
    messagingSenderId: '265396258247',
    projectId: 'personal-tommaso2212',
    storageBucket: 'personal-tommaso2212.appspot.com',
    iosClientId: '265396258247-bi6k0eqornnl87dl1113mqo993ngoeio.apps.googleusercontent.com',
    iosBundleId: 'com.example.personal',
  );
}
