import 'dart:convert';
import 'dart:math';
import 'package:flutter/services.dart';
import 'package:personal_website/pages/wordle/domain/repository/wordle_repository.dart';

class WordleRepositoryImpl implements WordleRepository {
  @override
  Future<void> fetchWordls() async {
    if (wordsEng.isEmpty) {
      final String response = await rootBundle.loadString('assets/wordle-5-letter-list.json');
      final data = await json.decode(response);
      wordsEng.addAll((data as List).map((e) => e as String));
    }
  }

  @override
  Future<String> getCorrectWord() async {
    var random = Random();
    var index = random.nextInt(wordsEng.length);
    return wordsEng[index];
  }

  @override
  Future<bool> validateWord(String word) async {
    return wordsEng.contains(word);
  }

  static final List<String> wordsEng = [];

  static const List<String> wordsIt = [
    'abito',
    'acqua',
    'aiuto',
    'altro',
    'amare',
    'amico',
    'amore',
    'ampio',
    'anche',
    'anima',
    'animo',
    'assai',
    'avere',
    'bagno',
    'basso',
    'bello',
    'bocca',
    'bosco',
    'bravo',
    'breve',
    'buono',
    'caffè',
    'caldo',
    'campo',
    'carne',
    'carta',
    'causa',
    'certo',
    'cielo',
    'circa',
    'città',
    'collo',
    'colpa',
    'colpo',
    'conto',
    'corpo',
    'corsa',
    'corso',
    'costa',
    'crisi',
    'croce',
    'cuore',
    'dente',
    'dolce',
    'donna',
    'entro',
    'epoca',
    'esame',
    'fatto',
    'fermo',
    'ferro',
    'festa',
    'fiore',
    'fiume',
    'folla',
    'fondo',
    'forma',
    'forse',
    'forte',
    'forza',
    'frase',
    'fuoco',
    'fuori',
    'gamba',
    'gatto',
    'gente',
    'gesto',
    'gioco',
    'gioia',
    'grado',
    'grave',
    'greco',
    'gusto',
    'isola',
    'largo',
    'latte',
    'legge',
    'letto',
    'libro',
    'linea',
    'lotta',
    'lungo',
    'luogo',
    'madre',
    'mamma',
    'massa',
    'medio',
    'mente',
    'messa',
    'metro',
    'mezzo',
    'molto',
    'mondo',
    'monte',
    'morte',
    'notte',
    'nulla',
    'nuovo',
    'odore',
    'oltre',
    'ombra',
    'onore',
    'opera',
    'padre',
    'paese',
    'parte',
    'passo',
    'paura',
    'pazzo',
    'pelle',
    'pezzo',
    'piano',
    'piede',
    'pieno',
    'pietà',
    'poeta',
    'ponte',
    'porre',
    'porta',
    'porto',
    'posto',
    'prato',
    'prima',
    'primo',
    'prova',
    'punta',
    'punto',
    'quale',
    'quasi',
    'reale',
    'regno',
    'resto',
    'ricco',
    'rosso',
    'russo',
    'sacro',
    'scala',
    'scena',
    'scopo',
    'segno',
    'senso',
    'senza',
    'serie',
    'serio',
    'sogno',
    'sonno',
    'sopra',
    'sotto',
    'spesa',
    'stare',
    'stato',
    'tanto',
    'tardi',
    'tempo',
    'terzo',
    'testa',
    'treno',
    'tutto',
    'udire',
    'umano',
    'unico',
    'unire',
    'usare',
    'utile',
    'valle',
    'vario',
    'vasto',
    'vento',
    'verde',
    'verso',
    'villa',
    'vista',
    'volta',
    'volto',
    'vuoto',
    'zitto'
  ];
}
